### PR TITLE
Update +page.server.ts

### PR DESCRIPTION
**Pull request by Annis-Monadjem**
In `cookies.set()` replace `maxAge` with `max-age` (reference: https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie)

### CODE REVIEW

**Comment by Annis-Monadjem** [comment]
In `cookies.set()` replace `maxAge` with `max-age` (reference: https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie)

**Comment by consultingninja** [comment]
Hey Annis.    You are correct that the cookie property is in fact 'max-age', however cookies.set() is a special method provided by SvelteKit.  If you use TypeScript and visit the typescript definition file for the .set() method they have a comment that they are using a cookie parser library for parts of that method (Relevant part here: * @param opts the options, passed directory to `cookie.serialize`. See documentation [here](https://github.com/jshttp/cookie#cookieserializename-value-options)
	 */" .  If you continue following the breadcrumbs and go look at this library here:  https://github.com/jshttp/cookie#cookieserializename-value-options .  In the section labeled 'OPTIONS' you will see that they have called this 'option' maxAge in their library, but it is in fact setting the max-age property of the cookie.  You can do a little test locally to see that when using maxAge ,the max-age property is in fact getting set correctly.  I hope this helps to clarify what is going on here!  Have a great day!

**Comment by Annis-Monadjem** [comment]
Thank you for detailed explanation. Very helpful.

**Comment by consultingninja** [comment]
> Thank you for detailed explanation. Very helpful.

Of course!  You are very welcome!  Thank you for jumping in with your thoughts!  Please continue to point out anything you think should be changed or improved.  The point of my channel is to help everyone learn and get better.  There are always ways things can be improved!

**Pull request closed without merging**
